export enum ApiEndpoints {
    CATEGORY = '/category',
    RECIPE = '/recipe',
    CATEGORY_RECIPES = '/recipe/category',
    SIGN_UP = '/auth/signup',
    LOGIN = '/auth/login',
    REFRESH = '/auth/refresh',
    CHECK_AUTH = '/auth/check-auth',
    FORGOT_PASSWORD = '/auth/forgot-password',
    VERIFY_OTP = '/auth/verify-otp',
    RESET_PASSWORD = '/auth/reset-password',
    MEASURE_UNITS = '/measure-units',
    FILE_UPLOAD = '/file/upload',
    RECIPE_DRAFT = '/recipe/draft',
}
